services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/uni_activities
      SPRING_DATASOURCE_USERNAME: uni
      SPRING_DATASOURCE_PASSWORD: uni
      STAFF_REG_CODE: letmein
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: uni_activities
      POSTGRES_USER: uni
      POSTGRES_PASSWORD: uni
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
